version: '3.8'

services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v23.3.10
    container_name: redpanda-broker
    command:
      - redpanda start
      - --overprovisioned
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --node-id 0
      - --check=false
    ports:
      - 9092:9092
      - 9644:9644

  console:
    image: docker.redpanda.com/redpandadata/console:v2.6.1
    container_name: redpanda-console
    ports:
      - 8080:8080
    environment:
      - CONFIG_FILEPATH=/app/config.yml
    volumes:
      - ./console-config.yml:/app/config.yml
    depends_on:
      - redpanda

  backend:
    image: rust:1.82
    container_name: rsi-backend
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: >
      bash -c "apt-get update &&
      apt-get install -y librdkafka-dev pkg-config cmake build-essential &&
      cargo build &&
      cargo run"
    depends_on:
      - redpanda
